### PR TITLE
Added support for manifest v3

### PR DESCRIPTION
**Pull request by pypp**
Chrome will end support for Manifest V2 extension.
so I added support for Manifest V3.

### CODE REVIEW

**Comment by shreshthmohan** [comment]
This also unintentionally fixes a bug.

The extension wasn't working with titles that has a `'` in it.

**Comment by shreshthmohan** [comment]
@1netanel it would be great if you published your own chrome extension 🙏🏽 (with due credit to @narinluangrath of course) as it looks like this repo has no activity for the past few years.

**Comment by 1netanel** [comment]
> @1netanel it would be great if you published your own chrome extension 🙏🏽 (with due credit to @narinluangrath of course) as it looks like this repo has no activity for the past few years.

I just did published it, if you want to check it or contribute to it you can check it here 
https://github.com/1netanel/numberedTabs

**Comment by pypp** [comment]
> @1netanel it would be great if you published your own chrome extension 🙏🏽 (with due credit to @narinluangrath of course) as it looks like this repo has no activity for the past few years.

Just created a repo, I will try to upload the extension in the next few days.

**Comment by pypp** [comment]
> @1netanel it would be great if you published your own chrome extension 🙏🏽 (with due credit to @narinluangrath of course) as it looks like this repo has no activity for the past few years.

It is now published you can check it here
https://chrome.google.com/webstore/detail/numbered-tabs/oiofagafohgjohjimdgaggjabocbhckl

**Comment by shreshthmohan** [comment]
I am using your extension now, thanks!

**Pull request closed without merging**
